name: Kitchensink Fuzz

on:
    push:
    pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-25.04

    steps:
    # Setup
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.cargo/
        key: dot-cargo
    # Workaround to afl config bug
    - run: sudo apt update
    - run: sudo apt install llvm-dev
    - run: sudo ln -s /usr/bin/llvm-dev /usr/bin/llvm-dev-20
    - run: rustup default nightly
    - run: cargo install ziggy cargo-afl
    - run: cargo afl config --build --force --plugins

    # Build
    - uses: actions/cache@v4
      with:
        path: substrate/bin/node/runtime/fuzzer/target
        key: target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build fuzzer
      env:
        SKIP_WASM_BUILD: true
      working-directory: substrate/bin/node/runtime/fuzzer
      run: cargo ziggy build --no-honggfuzz

    # Fuzz
    - uses: actions/cache@v4
      with:
        path: substrate/bin/node/runtime/fuzzer/output/kitchensink-fuzzer/corpus
        key: kitchensink-corpus
    - name: Fuzz for 15 minutes
      env:
        SKIP_WASM_BUILD: true
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: true
        AFL_SKIP_CPUFREQ: true
        AFLRS_REQUIRE_PLUGINS: true
        AFL_LLVM_ALLOWLIST: $(pwd)/allowlist.txt
      working-directory: substrate/bin/node/runtime/fuzzer
      run: timeout 15m cargo ziggy fuzz || [[ $? -eq 124 ]]

    # Finally
    - name: Upload Fuzzer Output
      uses: actions/upload-artifact@v4
      with:
          name: fuzzer-output
          path: substrate/bin/node/runtime/fuzzer/output/kitchensink-fuzzer/afl/mainaflfuzzer/fuzzer_stats

    - name: Get Coverage 
      run: |
        # TODO: 
        # This is a placeholder to get gcov report

    - name: Post the coverage report in PR
      run: |
        # TODO: 
        # This is a placeholder to post the coverage report in PR