name: Kitchensink Fuzz

on:
    pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-25.04

    steps:
    # Setup
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.cargo/
        key: dot-cargo
    # Workaround to afl config bug
    - run: wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
    - run: echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main" | sudo tee /etc/apt/sources.list.d/llvm.list
    - run: sudo apt update
    - run: sudo apt install llvm-20-dev
    - run: rustup default nightly
    - run: cargo install ziggy cargo-afl
    - run: cargo afl config --build --force --plugins

    # Build
    - uses: actions/cache@v4
      with:
        path: substrate/bin/node/runtime/fuzzer/target
        key: target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build fuzzer
      env:
        SKIP_WASM_BUILD: true
      working-directory: substrate/bin/node/runtime/fuzzer
      run: cargo ziggy build --no-honggfuzz

    # Fuzz
    - uses: actions/cache@v4
      with:
        path: substrate/bin/node/runtime/fuzzer/output/kitchensink-fuzzer/corpus
        key: kitchensink-corpus
    - name: Fuzz for 15 minutes
      env:
        SKIP_WASM_BUILD: true
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: true
        AFL_SKIP_CPUFREQ: true
        AFLRS_REQUIRE_PLUGINS: true
        AFL_LLVM_ALLOWLIST: $(pwd)/allowlist.txt
      working-directory: substrate/bin/node/runtime/fuzzer
      run: timeout 15m cargo ziggy fuzz -j 4 --no-honggfuzz || [[ $? -eq 124 ]]

    # Finally extract fuzzer metrics from fuzzer status 
    - name: Read Fuzzer metrics for status
      id: file_content
      run: |
            keys=("fuzz_time" "saved_crashes" "edges_found" "total_edges")
            for key in ${keys[@]}; do
              value=$(cat substrate/bin/node/runtime/fuzzer/output/kitchensink-fuzzer/afl/mainaflfuzzer/fuzzer_stats | grep $key | awk -F: '{print $2}')
              echo "${key}=${value}" | tee -a $GITHUB_OUTPUT
            done

    - name: Get Coverage Report
      run: |
        # TODO: 
        # This is a placeholder to get gcov report

    - name: Post comment on the PR
      # FIXME: Remove gurard condition once the action is finlaised to only for PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v3
      with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = `
            **Total Fuzzing Time (Duration)** : ${process.env.FUZZ_TIME}
            **No. of Crashes found** : ${process.env.SAVED_CRASHES}
            **Explored Edges** : ${process.env.EDGES_FOUND}
            **Total Edges** : ${process.env.TOTAL_EDGES}
            **Coverage** : ${(parseInt(process.env.EDGES_FOUND)/parseInt(process.env.TOTAL_EDGES)*100).toFixed(2)}%
            **Coverage Report** : Download here
            **Crash Report** : Refer here
            `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
      env:
        FUZZ_TIME: ${{ steps.file_content.outputs.fuzz_time }}
        SAVED_CRASHES: ${{ steps.file_content.outputs.saved_crashes }}
        EDGES_FOUND: ${{ steps.file_content.outputs.edges_found }}
        TOTAL_EDGES: ${{ steps.file_content.outputs.total_edges }}
  