name: Checkout Fuzzer Repo

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Srlabs runtime fuzzer repository
          uses: actions/checkout@v2
          with:
            repository: 'srlabs/substrate-runtime-fuzzer'
            path: 'runtime_fuzzer'
    
        - name: Locate Cargo.toml
          run: |
            cd runtime_fuzzer/templates/kitchensink/
            cat Cargo.toml
        
