name: Checkout Fuzzer Repo

on:
    push:
    pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fuzzer Repo
      uses: actions/checkout@v2
      with:
        repository: 'srlabs/substrate-runtime-fuzzer'
        path: 'runtime_fuzzer'

    - name: Install Rust target
      run: rustup target add wasm32-unknown-unknown

    - name: Install dependencies
      run: cargo install ziggy cargo-afl honggfuzz grcov
    
    - name: Run cargo ziggy fuzz for 1 minute
      run: |
        cd runtime_fuzzer/templates/kitchensink/
        export SKIP_WASM_BUILD=1
        timeout 15m cargo ziggy fuzz

    - name: Print Cargo.toml
      run: |
        cd runtime_fuzzer/templates/kitchensink/
        cat Cargo.toml

    - name: Send message to Element chat
      run: |
        # This is a placeholder for your script to send a message to Element chat
        echo "Sending message to Element chat..."



   
